### ISSUE TITLE
[Feature Request]: Pass PHP version to Psalm script

### ISSUE THREAD

**Issue by luislard** [inpsyde/reusable-workflows#16]
### Is your feature request related to a problem?

The psalm script can infer the php version from the composer.json. Normally we used in our composer.json 

```
...
"require": {
    "php": ">=7.4",
    ...
}
...
```
The configuration from above will make psalm always infer php7.4 as environment, but that can be described via CLI using the option --php-version

```
- name: Check Psalm
  run: vendor/bin/psalm --output-format=github --php-version=${{ matrix.php-versions }}
``` 

### Describe the desired solution

psalm running with specific inferred version according with PHP matrix

### Describe the alternatives that you have considered

Add the php-version option to psalm script

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chrico** [comment]
Thanks for your input. So we should add like described here https://psalm.dev/docs/running_psalm/configuration/#phpversion the current `--php-version` to psalm.

CC @tyrann0us
