### ISSUE TITLE
[Feature Request]: Node 16 LTS end of life Sep 2023

### ISSUE THREAD

**Issue by Chrico** [inpsyde/reusable-workflows#40]
### Is your feature request related to a problem?

Node version 16 LTS has end of life for security support on 11. Sep 2023 and had active support 18 Oct 2022.

### Describe the desired solution

We should consider upgrading our workflows (and packages) to Node 18 LTS - active support 18. Oct 2023 and security support 30. Apr 2025.

### Describe the alternatives that you have considered

We could also wait for Node 20 LTS to appear and use straight away the newest version. But first we need to check how support in libraries and build tools is in general for this version.

### Additional context

- https://endoflife.date/nodejs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shvlv** [comment]
The essential information we should be aware of is https://github.com/webpack/webpack/issues/14532. I.e. `webpack < v5.61.0` will not work on `node >= 17`. 
The same for https://github.com/WordPress/gutenberg/issues/36471. I.e. `@wordpress/dependency-extraction-webpack-plugin < 3.5.0` or `Gutenberg < 13.3.0` will not work on `node >=17`.
