### ISSUE TITLE
[Bug]: Release notes are overwritten

### ISSUE THREAD

**Issue by judy-inpsyde** [inpsyde/reusable-workflows#47]
### Description of the bug

The packages that are using [Build](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/build-assets-compilation.yml), release notes are overwritten with `Compiled assets available in....` lately.

This is potentially due to https://github.com/svenstaro/upload-release-action/blob/master/src/main.ts#L77-L83

They have introduced the `overwrite` option but we have it fixed here https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/build-assets-compilation.yml#L143

Example repos:
- https://github.com/inpsyde/gutenberg-dialogs/releases

### Reproduction instructions

1. Utilize https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/build-assets-compilation.yml with your package.
2. Create a release with notes.
3. Check the release note once the asset is built.

### Expected behavior

Release notes to not be overwritten. Perhaps, a new config/input that we can say `true` or `false` for the `overwrite` value.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tyrann0us** [comment]
> Perhaps, a new config/input that we can say `true` or `false` for the `overwrite` value.

I’d vote to remove the argument (it defaults to `false`) because I don’t see any reason why we’d want to overwrite custom release notes.
