### ISSUE TITLE
[Feature Request]: Use `npm ci` / `yarn --frozen-lockfile` for dependencies installation

### ISSUE THREAD

**Issue by shvlv** [inpsyde/reusable-workflows#55]
### Is your feature request related to a problem?

Not really.

### Describe the desired solution

Use `npm ci` / `yarn --frozen-lockfile` (`yarn install --prefer-offline --frozen-lockfile` as an option) for dependencies installation for workflows where asset compilation is required.

It speeds up dependencies installation and it's recommended way for CI environment.a 

### Describe the alternatives that you have considered

Do nothing.

### Additional context

This is a kind of breaking change because we must have `yarn.lock` or `package-json.lock` in the repository.

But in fact that breaking change [done already](https://github.com/inpsyde/reusable-workflows/commit/79a3c5794a5339f17a092a40ff25e68866ef7e15) because `actions/setup-node@v3` cache functionality requires lock file to be present. 

So all we need to make this clear with documentation.

The single workflow where the "old" cache is used is https://github.com/inpsyde/reusable-workflows/blob/3020c4df1f2543ab4ad05b48f68e5470f0b767ee/.github/workflows/build-assets-compilation.yml#L98-L104. It should be discussed do we need to align that with other workflows.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chrico** [comment]
We discussed this today (08.08.2023). First of all we need to align all node-based reusable-workflows. Right now we talk about fl

- wp-scripts-lint.yml	
- build-and-push-assets.yml	
- build-assets-compilation.yml (composer-asset-compiler)

All 3 workflows should contain following logic by adding a new ENV variable "CACHE_MODE":

1. If `PACKAGE_MANAGER` === `yarn` -> check `yarn.lock` exists -> CACHE_MODE = 'on'
2. If `PACKAGE_MANAGER` === `npm` -> check `package-json.lock` exists -> CACHE_MODE = 'on'
3. CACHE_MODE = "off"

This var is used in 2 scenarios:

**1. Configure caching**
In case we have "off", we want to set on `actions/setup-node@v3` the `cache: ''` (default), which will not cache it. If it is "on", we want to set it.

**2. Configure installation step**
In case we have `CACHE_MODE === "on"` we want to run `npm ci` or `yarn --frozen-lockfile`. If it is "off", we want to execute it normally.
