### ISSUE TITLE
[Feature Request]: Check TypeScript types

### ISSUE THREAD

**Issue by shvlv** [inpsyde/reusable-workflows#63]
### Is your feature request related to a problem?

Not really. But now if have a TypeScript-based project there is no possibility to verify the type system before asset compiling. This means we can't leverage TypeScript checks during PRs review.

### Describe the desired solution

The simplest solution is to run such a command: `tsc --noEmit -project ./tsconfig.eslint.json --skipLibCheck`. Sure will be nice to inline errors in the files view. But my quick GithHub search there is no maintained and ready-to-use GitHub action.

Maybe we could check https://github.com/Arhia/action-check-typescript but there are a lot of issues without a respond. 

So IMO small dependency-less command is better.

### Describe the alternatives that you have considered

Do nothing. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by widoz** [comment]
I've seen there are a couple of interesting arguments such as
- [noErrorTruncation](https://www.typescriptlang.org/tsconfig/#noErrorTruncation)
- [noUnusedLocals](https://www.typescriptlang.org/tsconfig/#noUnusedLocals)
- [noUnusedParameters](https://www.typescriptlang.org/tsconfig/#noUnusedParameters)
- ...

Have you also considered to have `tsc` as internal dev dep instead of installed globally? 

I agree if a dep can be avoided the better.

**Comment by Chrico** [comment]
We could install the `tsc` dependency globally in the reusable workflow itself via ` npm install -g typescript` - but normally you should have `typescript` defined in your `package.json`, right?

I'm wondering if we can solve the actualy problem here. While we can implement a reusable-workflow `lint-typescript.yml`, what about SCSS and other things which are also required for "successfully building assets"?

I've following scenario:

## Files

**test.scss**
```scss
foobarbaz []
```

**test.ts**
```ts
import '../scss/test.scss';
class Foo {
	constructor( private bar: string ) {}
}

new Foo( 1 );
```

---

## "Linting"

**1. Running TSC**
```shell
$ tsc --noEmit --skipLibCheck resources/ts/*
resources/ts/test.ts:6:10 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

6 new Foo( 1 );
           ~
Found 1 error in resources/ts/test.ts:6
```

**2. Running yarn build**
```shell
$ yarn build

// SNIP

Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
1 │ foobarbaz []
  │             ^
  ╵
  resources\scss\test.scss 1:13  root stylesheet

// SNIP

./resources/ts/test.ts 6:9-10
[tsl] ERROR in {snip}\resources\ts\test.ts(6,10)
      TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

2 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.88.2 compiled with 3 errors in 1684 ms
```

CC @tyrann0us

**Comment by Chrico** [comment]
While we see the benefit here, we first will try to make a Gutenberg ticket for that to solve this at "higher" level in a reusable/maintainable way: https://github.com/WordPress/gutenberg/issues/54305

**Comment by tyrann0us** [comment]
We raised this upstream in https://github.com/WordPress/gutenberg/issues/54305, which ideally will result in a new command for `@wordpress/scripts`, e.g., `lint-ts`.
Let's await feedback there (CC @karmatosed); putting this on hold for the time being.

**Comment by Chrico** [comment]
Just to give a short update. It seems like Gutenberg `@wordpress/eslint-plugin` has support out of the box for Typescript and already installs the right plugins: [gutenberg/packages/eslint-plugin#usage](https://github.com/WordPress/gutenberg/tree/76b0165002690569cc693fefc6b3e94e7e09204a/packages/eslint-plugin#usage). But because of a configuration error no type checks are excuted. To get around for it right now you can do following in your `package.json`:

```json
    "eslintConfig": {
        "rules": {
            "no-unused-vars": "error"
        }
    }
```

I'm currently in discussion in https://github.com/WordPress/gutenberg/issues/54305 , why they do `"no-unused-vars": "off"` in the default configuration.

**Comment by shvlv** [comment]
I've rechecked the issue and tested https://github.com/WordPress/gutenberg/pull/62925 alongside pure https://typescript-eslint.io/ locally and in the GitHub action environment. It doesn't fix the original problem of checking types during linting. The https://github.com/typescript-eslint/typescript-eslint/issues/352#issuecomment-472597115 issue explains why. `typescript-eslint` does not check types by design; the plugin purpose is to enforce codebase consistent based on some opinionated rules like `const x: Array<string> = ['a', 'b'];` is incorrect but `const x: string[] = ['a', 'b'];` (we can consider using some of those rules, but there are not strong benefits).

Moreover, the mentioned issue suggests to use TS compiler:
> If you want your code to be typechecked - please use tsc (or one of the tools built for your specific build chain).

The same can be found in the documentation - https://typescript-eslint.io/rules/typedef/:
> Instead of enabling typedef, it is generally recommended to use the --noImplicitAny and --strictPropertyInitialization compiler options to enforce type annotations only when useful.

So in the end, using of `tsc --noEmit` is the single way to do typecheck before the code gets merged to the main branch.

Regarding additional compiler options I think the best if we would run the type check command with the same options as we have in `tsconfig.json`. But if we are talking about enforcing of stricter types usage we can use `noImplicitAny` and `strictPropertyInitialization`. But this is might be project-specific and it's outside of the current issue.

**Comment by tyrann0us** [comment]
Thank you for your investigation! As discussed, please investigate the feasibility/possibility of adding typechecking to Gutenberg or rather `@wordpress/scripts`. Thank you!

**Comment by shvlv** [comment]
I've invested time in checking how type-checking happens inside Gutenberg.

The Gutenberg repository has "Static Analysis (Linting, License, Type checks...)" workflow with "Type checking" part - https://github.com/WordPress/gutenberg/blob/2e967be9e1928809841761744b4ed8c768f0a417/.github/workflows/static-checks.yml#L48-L49. This step `build:package-types`  run `tsc --build`  command. The command fails if type definitions are incorrect.

Therefore, if `typescript-eslint` maintainers suggest using the Typescript compiler and the Gutenberg project uses it, I don't see the reason not to use it to check types.

Note to say the way the Gutenberg project and Syde company use Typescript is very different. We use `ts-loader` instead of `babel-loader`, which comes with `@wordpress/scripts`. So Gutenberg uses Typescript compiler only to build types (note `declaration` and `emitDeclarationOnly` in the base config file - https://github.com/WordPress/gutenberg/blob/938a51387ff6c1b7f8c7a4ad4deb745afeff84d5/tsconfig.base.json#L11-L15 and `allowJs` - https://github.com/WordPress/gutenberg/blob/938a51387ff6c1b7f8c7a4ad4deb745afeff84d5/tsconfig.base.json#L4). So Gutenberg [generates types for JS files](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) as well and consumers can use Typescript definitions extracting from JS doc.
