### ISSUE TITLE
[Feature Request]: Deprecate `encore` scripts in assets compilation

### ISSUE THREAD

**Issue by tyrann0us** [inpsyde/reusable-workflows#85]
### Is your feature request related to a problem?

The `build-and-push-assets.yml` workflow uses `encore prod` and `encore dev` as defaults for the `COMPILE_SCRIPT_PROD` and `COMPILE_SCRIPT_DEV` inputs respectively: https://github.com/inpsyde/reusable-workflows/blob/af929128e7db96c868c54a9b04f18d0bad4885b9/.github/workflows/build-and-push-assets.yml#L31-L40

However, with the gradual move from Encore to `@wordpress/scripts` (see. e.g., #49), we should no longer default to Encore scripts.

### Describe the desired solution

Whenever a caller workflow uses Encore, e.g., by not setting the `COMPILE_SCRIPT_PROD`/`COMPILE_SCRIPT_DEV` inputs explicitly or by using custom Encore-based commands, we should output a deprecation warning, informing the user to use a different command (@Chrico, which one?).

### Describe the alternatives that you have considered

Instead of throwing a deprecating warning, we could immediately change the `COMPILE_SCRIPT_PROD`/`COMPILE_SCRIPT_DEV` input defaults. However, this would break BC, requiring instant changes in many caller workflows.

### Additional context

Changing the defaults mid-term will be handled in a different GitHub issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chrico** [comment]
I guess we can just align with our existing warnings we throw, like: https://github.com/inpsyde/reusable-workflows/blob/af929128e7db96c868c54a9b04f18d0bad4885b9/.github/workflows/build-assets-compilation.yml#L143

So we could just print out something like:

```
"::notice::The 'encore prod' and 'encore dev' default values are deprecated and will be replaced soon."
```

**Comment by Chrico** [comment]
As discussed in our meeting today, we are not going to add any notice. We will replace the following script defaults to align with `@wordpress/scripts`:

- `COMPILE_SCRIPT_PROD` -> `build` 
- `COMPILE_SCRIPT_DEV` -> `build:dev`

+ update documentation.
