### ISSUE TITLE
[Feature Request]: Current release reusable workflow does not expose a way of changing the token used or auth method

### ISSUE THREAD

**Issue by luislard** [inpsyde/reusable-workflows#86]
### Is your feature request related to a problem?

Current used secret name is too wide, and cannot be overridden.
See [here](https://github.com/inpsyde/reusable-workflows/blob/af929128e7db96c868c54a9b04f18d0bad4885b9/.github/workflows/automatic-release.yml#L60)

### Describe the desired solution

I suggest to make it configurable 

### Describe the alternatives that you have considered

Considered using a secret config USER_TOKEN.

Consider using SSH configuration.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luislard** [comment]
I tried keeping the name GITHUB_TOKEN but this var cant be overridden.

I got:
```
secret name `GITHUB_TOKEN` within `workflow_call` can not be used since it would collide with system reserved name
```

**Comment by tyrann0us** [comment]
According to the [documentation](https://github.com/semantic-release/semantic-release/blob/50a789638cf987d3be867854c08af7c669b2da2d/docs/recipes/git-hosted-services/git-auth-ssh-keys.md) linked on the page @luislard shared above, it is possible to use SSH keys for authentication as an alternative to using a token.

I wonder if using the `GITHUB_USER_*` secrets, specifically `GITHUB_USER_SSH_KEY`, would be sufficient as in other workflows that write to the repository ([example](https://github.com/inpsyde/reusable-workflows/blob/af929128e7db96c868c54a9b04f18d0bad4885b9/.github/workflows/build-and-push-assets.yml#L50-L58)). This would ensure that the methods of securing write permissions are the same for all workflows.

**Comment by luislard** [comment]
Tested using SSH but it failed:
Code: https://github.com/inpsyde/reusable-workflows/blob/e6477d0bc017b77245bb1cc69c2748fb5834ee06/.github/workflows/automatic-release.yml  
Error:
```
Command failed with exit code 128: git ls-remote --heads "https://github.com/<organization>/<package>
```

This is reported also in here https://github.com/semantic-release/github/issues/655 and the issue was closed as not planned.
